export const enum Duration {
  WHOLE = 'WHOLE',
  HALF = 'HALF',
  DOTTED_HALF = 'DOTTED_HALF',
  QUARTER = 'QUARTER',
  DOTTED_QUARTER = 'DOTTED_QUARTER',
  EIGHT = 'EIGHT',
  DOTTED_EIGHT = 'DOTTED_EIGHT',
  SIXTEENTH = 'SIXTEENTH',
  DOTTED_SIXTEENTH = 'DOTTED_SIXTEENTH',
}

export const enum Clef {
  BASS = 'Bass',
  TREBLE = 'Treble',
}

export const enum KeySignature {
  // No sharps or flats
  C_MAJOR_A_MINOR = 'C',
  // Sharp keys
  G_MAJOR_E_MINOR_1_SHARP = 'G',
  D_MAJOR_B_MINOR_2_SHARPS = 'D',
  A_MAJOR_F_SHARP_MINOR_3_SHARPS = 'A',
  E_MAJOR_C_SHARP_MINOR_4_SHARPS = 'E',
  B_MAJOR_G_SHARP_MINOR_5_SHARPS = 'B',
  F_SHARP_MAJOR_D_SHARP_MINOR_6_SHARPS = 'F#',
  C_SHARP_MAJOR_A_SHARP_MINOR_7_SHARPS = 'C#',
  // Flat keys
  F_MAJOR_D_MINOR_1_FLAT = 'F',
  Bb_MAJOR_G_MINOR_2_FLATS = 'Bb',
  Eb_MAJOR_C_MINOR_2_FLATS = 'Eb',
  Ab_MAJOR_F_MINOR_4_FLATS = 'Ab',
  Db_MAJOR_Bb_MINOR_5_FLATS = 'Db',
  Gb_MAJOR_Eb_MINOR_6_FLATS = 'Gb',
  Cb_MAJOR_Ab_MINOR_7_FLATS = 'Gb',
}
