export const enum Duration {
  WHOLE = 'WHOLE',
  DOTTED_WHOLE = 'DOTTED_WHOLE',
  HALF = 'HALF',
  DOTTED_HALF = 'DOTTED_HALF',
  QUARTER = 'QUARTER',
  DOTTED_QUARTER = 'DOTTED_QUARTER',
  EIGHTH = 'EIGHTH',
  DOTTED_EIGHT = 'DOTTED_EIGHT',
  SIXTEENTH = 'SIXTEENTH',
  DOTTED_SIXTEENTH = 'DOTTED_SIXTEENTH',
}
